name: Run Sipfront Call Test

on: [ pull_request, workflow_dispatch ]

jobs:
  sipfront-call-test:
    name: Validate, build, deploy and test end to end call
    runs-on: ubuntu-latest
    steps:

      # First, checkout the code
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      # Your pre-requisites steps go here to
      # * format and lint your code,
      # * build, push and deploy docker image to test system:
      #   https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

      # Then, trigger the test run:
      - name: Check basic end-to-end call from A to B
        id: testcall-1
        uses: sipfront/action-call-test@v0.0.7
        with:
          public_key: '${{ secrets.SIPFRONT_PUBLIC_KEY }}'
          secret_key: '${{ secrets.SIPFRONT_SECRET_KEY }}'
          name: 'basic-call-a-b'

      # Then, trigger the test run:
      - name: Check if DTMF is working
        id: testcall-2
        uses: sipfront/action-call-test@v0.0.7
        with:
          public_key: '${{ secrets.SIPFRONT_PUBLIC_KEY }}'
          secret_key: '${{ secrets.SIPFRONT_SECRET_KEY }}'
          name: 'validate-dtmf'  

      # You can also print the test session id used in the call test
      - name: Print Output
        id: output
        run: echo "${{ steps.testcall.outputs.session_id }}"
