name: Run Sipfront Call Test

on: [ pull_request, workflow_dispatch ]

jobs:
  sipfront-call-test:
    name: Test end-to-end call on Sipfront
    runs-on: ubuntu-latest
    steps:

      # Your pre-requisites steps go here to checkout, build and deploy
      # your changes to your test system, such as:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      # Then, trigger the test run:
      - name: Run end-to-end Sipfront call test
        id: testcall
        uses: sipfront/action-call-test@v0.0.7
        with:
          public_key: '${{ secrets.SIPFRONT_PUBLIC_KEY }}'
          secret_key: '${{ secrets.SIPFRONT_SECRET_KEY }}'
          name: 'basic-call-a-b'

      # You can also print the test session id used in the call test
      - name: Print Output
        id: output
        run: echo "${{ steps.testcall.outputs.session_id }}"